services:
  web:
    build: .
    command: poetry run gunicorn main:app -c gunicorn_conf.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
